"""
Disruption Monitor Agent
========================
Given a disruption event (crowd spike, cancellation, closure, weather)
targeting a specific slot, this agent decides whether the slot needs
to change and executes the swap using the slot's pre-computed Shadow
Itinerary alternatives.

The explanation shown to the user is generated by Claude when an API
key is available (grounded in the actual before/after data, so it
can't hallucinate a place that isn't the real alternative) and falls
back to a template otherwise.
"""
from datetime import datetime, timezone

from app.llm import LLMUnavailable, complete
from app.models import ActivitySlot, Alternative, BackupLogEntry, DisruptionType, TripState

_SYSTEM_PROMPT = """You write a single short, natural sentence (max 25 words) telling a \
traveler why their plan just changed. You're given the disruption, the original activity, \
and the replacement. Be specific and reassuring, not robotic. Do not invent details not given."""


class DisruptionMonitorAgent:
    def evaluate(self, state: TripState, slot_id: str, disruption_type: DisruptionType) -> dict:
        slot = self._find_slot(state, slot_id)
        if slot is None:
            return {"triggered": False, "reason": "slot not found"}

        if not slot.alternatives:
            return {"triggered": False, "reason": "no pre-ranked alternative available"}

        return {"triggered": True, "slot": slot, "disruption_type": disruption_type}

    def apply_swap(self, state: TripState, slot: ActivitySlot, disruption_type: DisruptionType) -> TripState:
        best_alt = slot.alternatives[0]
        original_name = slot.name
        original_crowd = slot.crowd_level

        slot.poi_id = best_alt.poi_id
        slot.name = best_alt.name
        slot.crowd_level = best_alt.crowd_level
        slot.cost = best_alt.cost
        slot.status = "swapped"
        slot.swap_reason = self._explain(disruption_type, original_name, original_crowd, best_alt)
        slot.alternatives = slot.alternatives[1:]  # remaining standbys stay ready

        state.backup_log.append(BackupLogEntry(
            slot_id=slot.slot_id,
            original=original_name,
            swapped_to=best_alt.name,
            reason=slot.swap_reason,
            timestamp=datetime.now(timezone.utc).isoformat(),
        ))
        return state

    def _explain(self, disruption_type: DisruptionType, original_name: str,
                 original_crowd: str, alt: Alternative) -> str:
        try:
            return self._explain_with_llm(disruption_type, original_name, original_crowd, alt)
        except LLMUnavailable:
            return self._explain_with_template(disruption_type, alt)

    def _explain_with_llm(self, disruption_type: DisruptionType, original_name: str,
                           original_crowd: str, alt: Alternative) -> str:
        user_message = (
            f"Disruption: {self._label(disruption_type)}\n"
            f"Original activity: {original_name} (crowd was {original_crowd})\n"
            f"Replacement: {alt.name} (crowd: {alt.crowd_level}, cost: {alt.cost})\n"
            f"Why this replacement was picked: {alt.reason}"
        )
        return complete(_SYSTEM_PROMPT, user_message, max_tokens=60)

    @staticmethod
    def _explain_with_template(disruption_type: DisruptionType, alt: Alternative) -> str:
        label = DisruptionMonitorAgent._label(disruption_type)
        return f"{label} → swapped to {alt.name} ({alt.reason})"

    @staticmethod
    def _find_slot(state: TripState, slot_id: str) -> ActivitySlot | None:
        for day in state.days:
            for slot in day.slots:
                if slot.slot_id == slot_id:
                    return slot
        return None

    @staticmethod
    def _label(disruption_type: DisruptionType) -> str:
        return {
            "crowd_spike": "Crowd spike detected",
            "cancelled": "Booking cancelled",
            "closed": "Venue closed",
            "weather": "Weather alert",
        }.get(disruption_type, "Disruption detected")


disruption_monitor_agent = DisruptionMonitorAgent()
